name: First Workflow
on: [push]
# Workflow can contain one or more jobs
# `jobs` is an object

jobs:
    run-shell-commands:
        runs-on: ubuntu-latest
        steps:
            - name: "echo a string"
              run: echo "Hello World"
            - name: "multiline Command"
              run: |
                uname -a
                hostname
                node -v
                npm -v
    parallel-job-macos:
        runs-on: macos-latest
        steps:
            - name: "Try to run a macos specific command"
              run: sw_vers
    dependant-job:
        runs-on: windows-latest
        # needs can be a job id, or an array of job id's
        needs: [
            run-shell-commands
        ]
        steps:
            - name: "echo a string"
              run: Write-Output "Windows String New"
            - name: Intentional Error Step
              run: doesnotexit

