name: First Workflow
on: [push]
# Workflow can contain one or more jobs
# `jobs` is an object

jobs:
    run-shell-commands:
        runs-on: ubuntu-latest
        steps:
            - name: "echo a string"
              run: echo "Hello World"
            - name: "multiline Command"
              run: |
                hostname
                node -v
                npm -v
