name: Working Dirs and Shells
on: [push]
# Setting bash shell here, will apply to all jobs including Windows
# Unless set at job level or at step. Check windows jobs next.
defaults:
  run:
    shell: bash
    # working-directory: /de/ed

jobs:
    display-wd-info:
        runs-on: ubuntu-latest
        steps:
            - name: Set working directory
              working-directory: /home/runner
              run: pwd
            - name: Display Working Dir & List Files
              run: |
                pwd
                ls -la
                echo $GITHUB_SHA
                echo $GITHUB_REPOSITORY
                echo $GITHUB_WORKSPACE
    display-wd-info-windows:
        runs-on: windows-latest
        defaults:
          run:
            shell: pwsh
        steps:
            - name: Display Working Dir & List Files on Windows
              run: |
                Get-Location
                dir
                echo $env:GITHUB_SHA
                echo $env:GITHUB_REPOSITORY
                echo $env:GITHUB_WORKSPACE
            - name: Python Shell
              shell: python
              run: |
                import platform
                print(platform.processor())
                    