name: Working Dirs and Shells
on: [push]

jobs:
    display-wd-info:
        runs-on: ubuntu-latest
        steps:
            - name: Display Working Dir & List Files
              run: |
                pwd
                ls -la
                echo $GITHUB_SHA
                echo $GITHUB_REPOSITORY
                echo $GITHUB_WORKSPACE
    display-wd-info-windows:
        runs-on: windows-latest
        steps:
            - name: Display Working Dir & List Files on Windows
              run: |
                Get-Location
                dir
                echo $env:$GITHUB_SHA
                echo $env:$GITHUB_REPOSITORY
                echo $env:$GITHUB_WORKSPACE
                    